# Identitas Service
server.port=8090
spring.application.name=auth-service

# Database H2 (Memory) - Cocok untuk Testing/Auth
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.settings.web-allow-others=true


# H2 Console (Untuk intip isi table user nanti)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registrasi ke Eureka (Jika kamu pakai Microservices)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Custom JWT (Opsional, agar gampang ganti secret key tanpa bongkar kode)
# jwt.secret=ini_adalah_kunci_rahasia_sangat_panjang_minimal_256_bits_ya
# jwt.expiration=3600000
