filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            regexp:
              container.image.name: '(filebeat|logstash|elasticsearch|kibana|prometheus|grafana|cadvisor)'

output.logstash:
  hosts: ["logstash:5044"]